name: "ClickHouse"
version: "1.0.0"
slug: "clickhouse"
description: "ClickHouse is a column-oriented database management system that allows generating analytical data reports in real time."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
ports:
  8123/tcp:
    description: "ClickHouse HTTP interface port."
    default: 8123
  9000/tcp:
    description: "ClickHouse native interface port."
    default: 9000
environment:
  CLICKHOUSE_DB: "homeassistant"
  CLICKHOUSE_USER: "homeassistant"
  CLICKHOUSE_PASSWORD: "homeassistant"